### ISSUE TITLE
Add javascript form validation

### ISSUE THREAD

**Issue by boekkooi** [fsi-open/admin-bundle#173]
I would like to propose to integrate JavaScript validation within the the admin bundle using [boekkooi/jquery-validation-bundle ~1.0](https://github.com/boekkooi/JqueryValidationBundle).

But before I create a PR integrating this bundle I would like to know if this would be considered for merging or if it would be better to add documentation on how to integrate the bundle with the admin bundle.

(P.S. another option would be to integrate [fp/jsformvalidator-bundle](https://packagist.org/packages/fp/jsformvalidator-bundle))

**Comment by szymach** [comment]
As far as my experience goes, I'd rather not integrate any JavaScript validators into the bundle. People tend to use whatever suits them in this regard, since each validator has it's pros and cons. A preferable solution would be to create an optional bundle that would provide a JavaScript validator and let the users decide whether they want it or not. Should it prove useful, it might be added as a recommended package in composer.json.

**Comment by boekkooi** [comment]
@szymach Since this bundle would only include 1 twig file would you accept it as a addition to the docs?

**Comment by szymach** [comment]
@boekkooi I will need to test the bundle first
